### PR TITLE
Tweeter streaming mode added

### PR DESCRIPTION
**Pull request by tsafin**
Added Twitter Streaming API code, which is fetching tweets in background, and web page which is calling to Cache' server via websocket API.

There is much to do (especially in the area of map visualization or effecient sentiment analysis), but it works more or less right now.

I'd appreciate  FE feedack from @iColdheart , server/websocket api feedback from @eduard93 and iknow application feedback from @ssolomaha

[Review on Reviewable](https://reviewable.io/reviews/intersystems-ru/iknowsocial/35)

### CODE REVIEW

**Comment by eduard93** [comment]
What is FE?

**Comment by eduard93** [comment]
TWReader/Streaming/Api.cls.xml 
TWReader/Streaming/Debug.cls.xml
 TWReader/UIBroker.cls.xml
 TWReader/WebSocket/Chunks.cls.xml 
 TWReader/WebSocket/Test.cls.xml

**Comment by tsafin** [comment]
@eduard93 By FE I meant all "front-end" stuff (i.e. CSS and client-side JS)

**Comment by eduard93** [comment]
ERROR #5475: Error compiling routine: Util.Data.Context:DomainName2DomainDef.  Errors:  
ERROR:Util.Data.Context.1(4) : SQLCODE=-29 : Field 'DEFINITIONCLASS' not found in the applicable tables
  `select DefinitionClass into [CompileRtns+193^%occRoutine:IKNOWSOCIAL]`

**Comment by tsafin** [comment]
@eduard93 странно, совершенно не ожидал такой несовместимости с такой близкой версией. Как-нибудь посмотрю 15.2, пока давай декларировать что только 16.1/16.2

**Pull request merged**
